import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavbarPage from './components/header';
import HeaderPage from './components/header';
import FooterPage from "./components/footer";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Portfolio using CSS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className="">
       <HeaderPage/>  
        <NavbarPage/>

        {children}
        <FooterPage/>

      </body>
    </html>
  );
}
